// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yamagame/school-api-gateway/infra/model"
)

func newChair(db *gorm.DB, opts ...gen.DOOption) chair {
	_chair := chair{}

	_chair.chairDo.UseDB(db, opts...)
	_chair.chairDo.UseModel(&model.Chair{})

	tableName := _chair.chairDo.TableName()
	_chair.ALL = field.NewAsterisk(tableName)
	_chair.ID = field.NewInt32(tableName, "id")
	_chair.LaboID = field.NewInt32(tableName, "labo_id")

	_chair.fillFieldMap()

	return _chair
}

type chair struct {
	chairDo chairDo

	ALL    field.Asterisk
	ID     field.Int32
	LaboID field.Int32

	fieldMap map[string]field.Expr
}

func (c chair) Table(newTableName string) *chair {
	c.chairDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c chair) As(alias string) *chair {
	c.chairDo.DO = *(c.chairDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *chair) updateTableName(table string) *chair {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.LaboID = field.NewInt32(table, "labo_id")

	c.fillFieldMap()

	return c
}

func (c *chair) WithContext(ctx context.Context) IChairDo { return c.chairDo.WithContext(ctx) }

func (c chair) TableName() string { return c.chairDo.TableName() }

func (c chair) Alias() string { return c.chairDo.Alias() }

func (c chair) Columns(cols ...field.Expr) gen.Columns { return c.chairDo.Columns(cols...) }

func (c *chair) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *chair) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 2)
	c.fieldMap["id"] = c.ID
	c.fieldMap["labo_id"] = c.LaboID
}

func (c chair) clone(db *gorm.DB) chair {
	c.chairDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c chair) replaceDB(db *gorm.DB) chair {
	c.chairDo.ReplaceDB(db)
	return c
}

type chairDo struct{ gen.DO }

type IChairDo interface {
	gen.SubQuery
	Debug() IChairDo
	WithContext(ctx context.Context) IChairDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IChairDo
	WriteDB() IChairDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IChairDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IChairDo
	Not(conds ...gen.Condition) IChairDo
	Or(conds ...gen.Condition) IChairDo
	Select(conds ...field.Expr) IChairDo
	Where(conds ...gen.Condition) IChairDo
	Order(conds ...field.Expr) IChairDo
	Distinct(cols ...field.Expr) IChairDo
	Omit(cols ...field.Expr) IChairDo
	Join(table schema.Tabler, on ...field.Expr) IChairDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IChairDo
	RightJoin(table schema.Tabler, on ...field.Expr) IChairDo
	Group(cols ...field.Expr) IChairDo
	Having(conds ...gen.Condition) IChairDo
	Limit(limit int) IChairDo
	Offset(offset int) IChairDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IChairDo
	Unscoped() IChairDo
	Create(values ...*model.Chair) error
	CreateInBatches(values []*model.Chair, batchSize int) error
	Save(values ...*model.Chair) error
	First() (*model.Chair, error)
	Take() (*model.Chair, error)
	Last() (*model.Chair, error)
	Find() ([]*model.Chair, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Chair, err error)
	FindInBatches(result *[]*model.Chair, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Chair) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IChairDo
	Assign(attrs ...field.AssignExpr) IChairDo
	Joins(fields ...field.RelationField) IChairDo
	Preload(fields ...field.RelationField) IChairDo
	FirstOrInit() (*model.Chair, error)
	FirstOrCreate() (*model.Chair, error)
	FindByPage(offset int, limit int) (result []*model.Chair, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IChairDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c chairDo) Debug() IChairDo {
	return c.withDO(c.DO.Debug())
}

func (c chairDo) WithContext(ctx context.Context) IChairDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c chairDo) ReadDB() IChairDo {
	return c.Clauses(dbresolver.Read)
}

func (c chairDo) WriteDB() IChairDo {
	return c.Clauses(dbresolver.Write)
}

func (c chairDo) Session(config *gorm.Session) IChairDo {
	return c.withDO(c.DO.Session(config))
}

func (c chairDo) Clauses(conds ...clause.Expression) IChairDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c chairDo) Returning(value interface{}, columns ...string) IChairDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c chairDo) Not(conds ...gen.Condition) IChairDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c chairDo) Or(conds ...gen.Condition) IChairDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c chairDo) Select(conds ...field.Expr) IChairDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c chairDo) Where(conds ...gen.Condition) IChairDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c chairDo) Order(conds ...field.Expr) IChairDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c chairDo) Distinct(cols ...field.Expr) IChairDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c chairDo) Omit(cols ...field.Expr) IChairDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c chairDo) Join(table schema.Tabler, on ...field.Expr) IChairDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c chairDo) LeftJoin(table schema.Tabler, on ...field.Expr) IChairDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c chairDo) RightJoin(table schema.Tabler, on ...field.Expr) IChairDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c chairDo) Group(cols ...field.Expr) IChairDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c chairDo) Having(conds ...gen.Condition) IChairDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c chairDo) Limit(limit int) IChairDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c chairDo) Offset(offset int) IChairDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c chairDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IChairDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c chairDo) Unscoped() IChairDo {
	return c.withDO(c.DO.Unscoped())
}

func (c chairDo) Create(values ...*model.Chair) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c chairDo) CreateInBatches(values []*model.Chair, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c chairDo) Save(values ...*model.Chair) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c chairDo) First() (*model.Chair, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Chair), nil
	}
}

func (c chairDo) Take() (*model.Chair, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Chair), nil
	}
}

func (c chairDo) Last() (*model.Chair, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Chair), nil
	}
}

func (c chairDo) Find() ([]*model.Chair, error) {
	result, err := c.DO.Find()
	return result.([]*model.Chair), err
}

func (c chairDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Chair, err error) {
	buf := make([]*model.Chair, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c chairDo) FindInBatches(result *[]*model.Chair, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c chairDo) Attrs(attrs ...field.AssignExpr) IChairDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c chairDo) Assign(attrs ...field.AssignExpr) IChairDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c chairDo) Joins(fields ...field.RelationField) IChairDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c chairDo) Preload(fields ...field.RelationField) IChairDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c chairDo) FirstOrInit() (*model.Chair, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Chair), nil
	}
}

func (c chairDo) FirstOrCreate() (*model.Chair, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Chair), nil
	}
}

func (c chairDo) FindByPage(offset int, limit int) (result []*model.Chair, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c chairDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c chairDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c chairDo) Delete(models ...*model.Chair) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *chairDo) withDO(do gen.Dao) *chairDo {
	c.DO = *do.(*gen.DO)
	return c
}
