// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yamagame/school-api-gateway/infra/model"
)

func newDesk(db *gorm.DB, opts ...gen.DOOption) desk {
	_desk := desk{}

	_desk.deskDo.UseDB(db, opts...)
	_desk.deskDo.UseModel(&model.Desk{})

	tableName := _desk.deskDo.TableName()
	_desk.ALL = field.NewAsterisk(tableName)
	_desk.ID = field.NewInt32(tableName, "id")
	_desk.LaboID = field.NewInt32(tableName, "labo_id")
	_desk.Name = field.NewString(tableName, "name")
	_desk.ProductCode = field.NewString(tableName, "product_code")

	_desk.fillFieldMap()

	return _desk
}

type desk struct {
	deskDo deskDo

	ALL         field.Asterisk
	ID          field.Int32
	LaboID      field.Int32
	Name        field.String
	ProductCode field.String

	fieldMap map[string]field.Expr
}

func (d desk) Table(newTableName string) *desk {
	d.deskDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d desk) As(alias string) *desk {
	d.deskDo.DO = *(d.deskDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *desk) updateTableName(table string) *desk {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt32(table, "id")
	d.LaboID = field.NewInt32(table, "labo_id")
	d.Name = field.NewString(table, "name")
	d.ProductCode = field.NewString(table, "product_code")

	d.fillFieldMap()

	return d
}

func (d *desk) WithContext(ctx context.Context) IDeskDo { return d.deskDo.WithContext(ctx) }

func (d desk) TableName() string { return d.deskDo.TableName() }

func (d desk) Alias() string { return d.deskDo.Alias() }

func (d desk) Columns(cols ...field.Expr) gen.Columns { return d.deskDo.Columns(cols...) }

func (d *desk) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *desk) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 4)
	d.fieldMap["id"] = d.ID
	d.fieldMap["labo_id"] = d.LaboID
	d.fieldMap["name"] = d.Name
	d.fieldMap["product_code"] = d.ProductCode
}

func (d desk) clone(db *gorm.DB) desk {
	d.deskDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d desk) replaceDB(db *gorm.DB) desk {
	d.deskDo.ReplaceDB(db)
	return d
}

type deskDo struct{ gen.DO }

type IDeskDo interface {
	gen.SubQuery
	Debug() IDeskDo
	WithContext(ctx context.Context) IDeskDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeskDo
	WriteDB() IDeskDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeskDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeskDo
	Not(conds ...gen.Condition) IDeskDo
	Or(conds ...gen.Condition) IDeskDo
	Select(conds ...field.Expr) IDeskDo
	Where(conds ...gen.Condition) IDeskDo
	Order(conds ...field.Expr) IDeskDo
	Distinct(cols ...field.Expr) IDeskDo
	Omit(cols ...field.Expr) IDeskDo
	Join(table schema.Tabler, on ...field.Expr) IDeskDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeskDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeskDo
	Group(cols ...field.Expr) IDeskDo
	Having(conds ...gen.Condition) IDeskDo
	Limit(limit int) IDeskDo
	Offset(offset int) IDeskDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeskDo
	Unscoped() IDeskDo
	Create(values ...*model.Desk) error
	CreateInBatches(values []*model.Desk, batchSize int) error
	Save(values ...*model.Desk) error
	First() (*model.Desk, error)
	Take() (*model.Desk, error)
	Last() (*model.Desk, error)
	Find() ([]*model.Desk, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Desk, err error)
	FindInBatches(result *[]*model.Desk, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Desk) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeskDo
	Assign(attrs ...field.AssignExpr) IDeskDo
	Joins(fields ...field.RelationField) IDeskDo
	Preload(fields ...field.RelationField) IDeskDo
	FirstOrInit() (*model.Desk, error)
	FirstOrCreate() (*model.Desk, error)
	FindByPage(offset int, limit int) (result []*model.Desk, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeskDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deskDo) Debug() IDeskDo {
	return d.withDO(d.DO.Debug())
}

func (d deskDo) WithContext(ctx context.Context) IDeskDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deskDo) ReadDB() IDeskDo {
	return d.Clauses(dbresolver.Read)
}

func (d deskDo) WriteDB() IDeskDo {
	return d.Clauses(dbresolver.Write)
}

func (d deskDo) Session(config *gorm.Session) IDeskDo {
	return d.withDO(d.DO.Session(config))
}

func (d deskDo) Clauses(conds ...clause.Expression) IDeskDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deskDo) Returning(value interface{}, columns ...string) IDeskDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deskDo) Not(conds ...gen.Condition) IDeskDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deskDo) Or(conds ...gen.Condition) IDeskDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deskDo) Select(conds ...field.Expr) IDeskDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deskDo) Where(conds ...gen.Condition) IDeskDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deskDo) Order(conds ...field.Expr) IDeskDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deskDo) Distinct(cols ...field.Expr) IDeskDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deskDo) Omit(cols ...field.Expr) IDeskDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deskDo) Join(table schema.Tabler, on ...field.Expr) IDeskDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deskDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeskDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deskDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeskDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deskDo) Group(cols ...field.Expr) IDeskDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deskDo) Having(conds ...gen.Condition) IDeskDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deskDo) Limit(limit int) IDeskDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deskDo) Offset(offset int) IDeskDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeskDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deskDo) Unscoped() IDeskDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deskDo) Create(values ...*model.Desk) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deskDo) CreateInBatches(values []*model.Desk, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deskDo) Save(values ...*model.Desk) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deskDo) First() (*model.Desk, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Desk), nil
	}
}

func (d deskDo) Take() (*model.Desk, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Desk), nil
	}
}

func (d deskDo) Last() (*model.Desk, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Desk), nil
	}
}

func (d deskDo) Find() ([]*model.Desk, error) {
	result, err := d.DO.Find()
	return result.([]*model.Desk), err
}

func (d deskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Desk, err error) {
	buf := make([]*model.Desk, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deskDo) FindInBatches(result *[]*model.Desk, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deskDo) Attrs(attrs ...field.AssignExpr) IDeskDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deskDo) Assign(attrs ...field.AssignExpr) IDeskDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deskDo) Joins(fields ...field.RelationField) IDeskDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deskDo) Preload(fields ...field.RelationField) IDeskDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deskDo) FirstOrInit() (*model.Desk, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Desk), nil
	}
}

func (d deskDo) FirstOrCreate() (*model.Desk, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Desk), nil
	}
}

func (d deskDo) FindByPage(offset int, limit int) (result []*model.Desk, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deskDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deskDo) Delete(models ...*model.Desk) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deskDo) withDO(do gen.Dao) *deskDo {
	d.DO = *do.(*gen.DO)
	return d
}
