// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: school/school.proto

package school

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 研究室の情報
type Labo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Group    string `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Program  string `protobuf:"bytes,4,opt,name=program,proto3" json:"program,omitempty"`
	Building string `protobuf:"bytes,5,opt,name=building,proto3" json:"building,omitempty"`
}

func (x *Labo) Reset() {
	*x = Labo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_school_school_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Labo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Labo) ProtoMessage() {}

func (x *Labo) ProtoReflect() protoreflect.Message {
	mi := &file_school_school_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Labo.ProtoReflect.Descriptor instead.
func (*Labo) Descriptor() ([]byte, []int) {
	return file_school_school_proto_rawDescGZIP(), []int{0}
}

func (x *Labo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Labo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Labo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Labo) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *Labo) GetBuilding() string {
	if x != nil {
		return x.Building
	}
	return ""
}

// The request message containing the user's name
type ListLabosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageSize *int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	Offset   *int32 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
}

func (x *ListLabosRequest) Reset() {
	*x = ListLabosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_school_school_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLabosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLabosRequest) ProtoMessage() {}

func (x *ListLabosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_school_school_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLabosRequest.ProtoReflect.Descriptor instead.
func (*ListLabosRequest) Descriptor() ([]byte, []int) {
	return file_school_school_proto_rawDescGZIP(), []int{1}
}

func (x *ListLabosRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListLabosRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

// The response message containing the greetings
type ListLabosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Labos  []*Labo `protobuf:"bytes,1,rep,name=labos,proto3" json:"labos,omitempty"`
	Offset int32   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListLabosResponse) Reset() {
	*x = ListLabosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_school_school_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLabosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLabosResponse) ProtoMessage() {}

func (x *ListLabosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_school_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLabosResponse.ProtoReflect.Descriptor instead.
func (*ListLabosResponse) Descriptor() ([]byte, []int) {
	return file_school_school_proto_rawDescGZIP(), []int{2}
}

func (x *ListLabosResponse) GetLabos() []*Labo {
	if x != nil {
		return x.Labos
	}
	return nil
}

func (x *ListLabosResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_school_school_proto protoreflect.FileDescriptor

var file_school_school_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2f, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x76, 0x0a, 0x04, 0x4c,
	0x61, 0x62, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x69, 0x6e, 0x67, 0x22, 0x6a, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x61, 0x62, 0x6f, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22,
	0x4f, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x61, 0x62, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x6f, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2e, 0x4c, 0x61, 0x62,
	0x6f, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x32, 0x66, 0x0a, 0x05, 0x53, 0x68, 0x6f, 0x6f, 0x6c, 0x12, 0x5d, 0x0a, 0x09, 0x4c, 0x69, 0x73,
	0x74, 0x4c, 0x61, 0x62, 0x6f, 0x73, 0x12, 0x18, 0x2e, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x4c, 0x61, 0x62, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x61,
	0x62, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x15, 0x3a, 0x01, 0x2a, 0x22, 0x10, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x63, 0x68, 0x6f,
	0x6f, 0x6c, 0x2f, 0x6c, 0x61, 0x62, 0x6f, 0x73, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x61, 0x6d, 0x61, 0x67, 0x61, 0x6d, 0x65, 0x2f,
	0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_school_school_proto_rawDescOnce sync.Once
	file_school_school_proto_rawDescData = file_school_school_proto_rawDesc
)

func file_school_school_proto_rawDescGZIP() []byte {
	file_school_school_proto_rawDescOnce.Do(func() {
		file_school_school_proto_rawDescData = protoimpl.X.CompressGZIP(file_school_school_proto_rawDescData)
	})
	return file_school_school_proto_rawDescData
}

var file_school_school_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_school_school_proto_goTypes = []any{
	(*Labo)(nil),              // 0: school.Labo
	(*ListLabosRequest)(nil),  // 1: school.ListLabosRequest
	(*ListLabosResponse)(nil), // 2: school.ListLabosResponse
}
var file_school_school_proto_depIdxs = []int32{
	0, // 0: school.ListLabosResponse.labos:type_name -> school.Labo
	1, // 1: school.Shool.ListLabos:input_type -> school.ListLabosRequest
	2, // 2: school.Shool.ListLabos:output_type -> school.ListLabosResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_school_school_proto_init() }
func file_school_school_proto_init() {
	if File_school_school_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_school_school_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Labo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_school_school_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListLabosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_school_school_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListLabosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_school_school_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_school_school_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_school_school_proto_goTypes,
		DependencyIndexes: file_school_school_proto_depIdxs,
		MessageInfos:      file_school_school_proto_msgTypes,
	}.Build()
	File_school_school_proto = out.File
	file_school_school_proto_rawDesc = nil
	file_school_school_proto_goTypes = nil
	file_school_school_proto_depIdxs = nil
}
