POST http://localhost:8090/v1/school/labos HTTP/1.1
content-type: application/json

{
}

###
POST http://localhost:8090/v1/school/labos HTTP/1.1
content-type: application/json

{
    "page_size": 10
}

###
POST http://localhost:8090/v1/school/labos HTTP/1.1
content-type: application/json

{
    "offset": 5
}
